# in .cargo/config.toml

# enabling to compile core package instead of using precompiled versions
# that come with rust installation.
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target="x86-64-rust_os.json"